### ISSUE TITLE
Error de carga del código CSS

### ISSUE THREAD

**Issue by cborcar637** [ibonper0708/Reforestacion-del-Amazonas#1]
El archivo HTML intenta cargar el CSS a través de un archivo llamado "estilo.css" que se encuentra en la carpeta "css". Sin embargo, no existe ninguna carpeta llamada "css" y el archivo "estilo.css" se encuentra en la raíz del proyecto.

Se debe crear una carpeta llamada "css" y meter ahí el archivo "estilo.css".

**Comment by ibonper0708** [comment]
Ha sido solucionada por el profesor.
